### PR TITLE
Fixed the random number generators.

### PR DESCRIPTION
**Pull request by caglar**
Set default seed for all the random number generators in the LSTM code.

### CODE REVIEW

**Comment by nouiz** [comment]
Thanks, the code also use the python random module, not just numpy random. Can you change the code to only use numpy random module? That could remove the not deterministic behavior you are seeing.

**Comment by caglar** [comment]
@nouiz thanks, it seems like you are right, mixing python number generator and numpy's seem to cause some non-deterministic behaviors. Changing python's random number generator to numpy's seem to fix the problem with this script.

**Comment by nouiz** [comment]
The random come from the fac that they are independent rng. seeding python rng could have also fixed this. But I prefer to use only one if there isn't a good reason. I'll merge this PR when travis pass.

thanks

**Comment by caglar** [comment]
Hi @nouiz I was already seeding the python rng as well.

**Comment by caglar** [comment]
Here is the line that I set the seed in my prev commit:
https://github.com/caglar/DeepLearningTutorials/blob/423f54d2daa67c02196737f17fc4365df6de76a1/code/lstm.py#L22

Anyways the tests are passing now.

**Pull request merged**
