### PR TITLE
Explicitly install "six" since theano is installed with "--no-deps"

### PR DESCRIPTION
**Pull request by lamblin**

### CODE REVIEW

**Comment by lamblin** [comment]
This fixes the build and does not change the code, so I'm merging.

**Comment by nouiz** [comment]
We install Theano with --no-deps. Good fix.

**Comment by abergeron** [comment]
Should we stop passing --no-deps?  This should still use the packages we install from the OS above, but would avoid problems like this in the future.

**Comment by nouiz** [comment]
not sure.... But if someone make a PR and it pass, I think we can merge it.

**Comment by abergeron** [comment]
Well: #94

**Pull request merged**
